Document: phoebetria
Title: Debian phoebetria Manual
Author: <insert document author here>
Abstract: This manual describes what phoebetria is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/phoebetria/phoebetria.sgml.gz

Format: postscript
Files: /usr/share/doc/phoebetria/phoebetria.ps.gz

Format: text
Files: /usr/share/doc/phoebetria/phoebetria.text.gz

Format: HTML
Index: /usr/share/doc/phoebetria/html/index.html
Files: /usr/share/doc/phoebetria/html/*.html
